services:
  diagnostics-app:
    build: .
    container_name: diagnostics-app
    ports:
      - "8000:8000"
    volumes:
      - ./reports:/app/reports
    restart: always

  node-red:
    image: nodered/node-red:latest
    container_name: node-red-app
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    restart: always
    depends_on:
      - diagnostics-app

volumes:
  node_red_data: